### ISSUE TITLE
Route collisions with lagom-scala-openshift-smoketests

### ISSUE THREAD

**Issue by ignasi35** [lagom/lagom-java-openshift-smoketests#12]
Both `lagom-scala-openshift-smoketests` and this repo use the same routes and `Host`:

```yaml
spec:
  host: my-lagom-openshift-smoketests.example.org
  path: /api/hello
spec:
  host: my-lagom-openshift-smoketests.example.org
  path: /proxy/rest-hello
```

Suprisingly, OpenShift doesn't complain about the ambiguity. This causes false positives if both applications are deployed simultaneously (I just got a `200 OK` when my scala pods were still running).

We should rename `path` and `host` on the two repos.
